#!/usr/bin/env python3
"""Compose the documentation artwork for codex-imagegen-mcp.

Every picture in docs/assets was generated with codex-imagegen-mcp itself; the prompts are listed
in docs/assets/README.md. This script turns those raw generations into the committed assets:

  * posters  - page banners and the README hero, with exact wording typeset locally in a slab serif
               (never generated by the model) on a cream paper margin
  * logo     - the emblem, trimmed, with the service's near-opaque alpha (251-254) snapped to 255
  * badges   - the six feature badges sliced out of one generated 3x2 grid
  * sheets   - the showcase contact sheets (aspect ratios, background removal, a real session)
  * social   - the 1280x640 repository social preview

Requirements: Python 3.9+, Pillow, numpy and the Superclarendon typeface (ships with macOS).

Usage:
  python3 scripts/compose-doc-art.py --art tmp/art --out docs/assets
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
from PIL import Image, ImageDraw, ImageFont

FONT_FILE = "/System/Library/Fonts/Supplemental/SuperClarendon.ttc"
BOLD, BLACK = 5, 7

# Palette C07 "Desert Modern" (the art direction record lives in docs/assets/README.md).
CREAM = (228, 217, 198)
PAPER = (237, 228, 210)
PAPER_LIGHT = (245, 239, 227)
OCHRE = (217, 160, 91)
RUST = (166, 85, 59)
INK = (42, 37, 35)

POSTER_WIDTH = 1600
THUMB_WIDTH = 640

BANNERS = {
    "docs": ("DOCUMENTATION", "A FIELD GUIDE TO CODEX IMAGEGEN MCP"),
    "auth": ("AUTHENTICATION", "SIGN-IN  ·  TOKENS  ·  REFRESH  ·  SECURITY"),
    "tools": ("TOOLS", "GENERATE  ·  EDIT  ·  CUT OUT  ·  STATUS  ·  SIGN IN"),
    "clients": ("CLIENTS", "OPENCODE  ·  CLAUDE CODE  ·  CURSOR  ·  VS CODE  ·  MORE"),
    "backend": ("BACKEND", "HOW CODEX IMAGE GENERATION REALLY WORKS"),
    "architecture": ("ARCHITECTURE", "MODULES  ·  REQUEST FLOW  ·  DESIGN DECISIONS"),
    "development": ("DEVELOPMENT", "BUILD  ·  TEST  ·  MOCK SERVER  ·  RELEASE"),
}
HERO_TITLE = ("CODEX IMAGEGEN MCP", "IMAGE GENERATION FOR EVERY CODING AGENT")

# Row-major order of the generated badge grid.
BADGES = ["signin", "clients", "transparency", "aspect", "versions", "skill"]


# ------------------------------------------------------------------------------------------ type


def font(size: int, face: int = BOLD) -> ImageFont.FreeTypeFont:
    return ImageFont.truetype(FONT_FILE, size, index=face)


def cap_height(f: ImageFont.FreeTypeFont) -> int:
    return -f.getbbox("H", anchor="ls")[1]


def tracked_width(text: str, f: ImageFont.FreeTypeFont, tracking: float) -> float:
    return sum(f.getlength(c) for c in text) + tracking * max(0, len(text) - 1)


def draw_centered(draw: ImageDraw.ImageDraw, cx: float, baseline: float, text: str, f, fill, tracking: float) -> float:
    """Letterspaced text centred on cx, sitting on `baseline`. Returns the set width."""
    width = tracked_width(text, f, tracking)
    x = cx - width / 2
    for c in text:
        draw.text((x, baseline), c, font=f, fill=fill, anchor="ls")
        x += f.getlength(c) + tracking
    return width


# ----------------------------------------------------------------------------------------- paper


def paper(size: tuple[int, int], seed: int = 11, base=PAPER, grain: float = 3.2) -> Image.Image:
    """Uncoated cream stock with a faint deterministic grain, so reruns are byte-stable."""
    w, h = size
    rng = np.random.default_rng(seed)
    noise = rng.normal(0.0, grain, (h, w, 1))
    arr = np.clip(np.array(base, dtype=np.float32)[None, None, :] + noise, 0, 255).astype(np.uint8)
    return Image.fromarray(arr, "RGB")


def keyline(draw: ImageDraw.ImageDraw, box: tuple[int, int, int, int], width: int = 2) -> None:
    x0, y0, x1, y1 = box
    draw.rectangle([x0 - width, y0 - width, x1 + width - 1, y1 + width - 1], outline=INK, width=width)


def checkerboard(size: tuple[int, int], cell: int = 24) -> Image.Image:
    w, h = size
    yy, xx = np.mgrid[0:h, 0:w]
    light = ((xx // cell + yy // cell) % 2 == 0)[..., None]
    arr = np.where(light, np.array(PAPER_LIGHT, np.uint8), np.array((226, 216, 197), np.uint8))
    return Image.fromarray(arr.astype(np.uint8), "RGB")


# ----------------------------------------------------------------------------------------- alpha


def snap_alpha(img: Image.Image, low: int = 6, high: int = 240) -> Image.Image:
    """The service returns 251-254 alpha inside opaque areas; make those fully opaque."""
    img = img.convert("RGBA")
    a = np.array(img.getchannel("A"))
    a = np.where(a >= high, 255, np.where(a <= low, 0, a)).astype(np.uint8)
    img.putalpha(Image.fromarray(a, "L"))
    return img


def square_pad(img: Image.Image, pad: float) -> Image.Image:
    bbox = img.getchannel("A").point(lambda v: 255 if v > 8 else 0).getbbox()
    img = img.crop(bbox)
    side = round(max(img.size) * (1 + 2 * pad))
    canvas = Image.new("RGBA", (side, side), (0, 0, 0, 0))
    canvas.paste(img, ((side - img.width) // 2, (side - img.height) // 2), img)
    return canvas


def on_checkerboard(img: Image.Image, cell: int = 24) -> Image.Image:
    base = checkerboard(img.size, cell).convert("RGBA")
    base.alpha_composite(img.convert("RGBA"))
    return base.convert("RGB")


# --------------------------------------------------------------------------------------- posters


def poster(art: Image.Image, title: str, subtitle: str, width: int = POSTER_WIDTH, margin: int = 26,
           height: int | None = None, crop_top: float = 0.3, title_size: int = 64, sub_size: int = 26,
           seed: int = 11) -> Image.Image:
    """Art on a cream paper margin with a keyline, and a slab-serif title block below it."""
    inner = width - 2 * margin
    # Auto-fit the subtitle so it (and its flanking rules) always keeps clear margins.
    while sub_size > 14:
        rule, space = round(sub_size * 2.2), round(sub_size * 0.8)
        if tracked_width(subtitle, font(sub_size, BOLD), sub_size * 0.26) + 2 * (rule + space) <= inner - 120:
            break
        sub_size -= 1
    tf, sf = font(title_size, BLACK), font(sub_size, BOLD)
    t_cap, s_cap = cap_height(tf), cap_height(sf)
    gap_top, gap_mid, gap_bottom = round(title_size * 0.55), round(title_size * 0.42), round(title_size * 0.55)
    band = gap_top + t_cap + gap_mid + s_cap + gap_bottom

    art = art.convert("RGB")
    art = art.resize((inner, round(art.height * inner / art.width)), Image.LANCZOS)
    if height is not None:
        art_h = height - margin - band
        excess = art.height - art_h
        if excess < 0:
            raise SystemExit(f"art too short for a {width}x{height} poster")
        top = round(excess * crop_top)
        art = art.crop((0, top, inner, top + art_h))
    total_h = margin + art.height + band

    canvas = paper((width, total_h), seed=seed)
    canvas.paste(art, (margin, margin))
    draw = ImageDraw.Draw(canvas)
    keyline(draw, (margin, margin, margin + inner, margin + art.height))

    cx = width / 2
    t_base = margin + art.height + gap_top + t_cap
    draw_centered(draw, cx, t_base, title, tf, INK, tracking=title_size * 0.16)
    s_base = t_base + gap_mid + s_cap
    s_width = draw_centered(draw, cx, s_base, subtitle, sf, RUST, tracking=sub_size * 0.26)
    rule_y = s_base - s_cap / 2
    rule, space = round(sub_size * 2.2), round(sub_size * 0.8)
    for x0 in (cx - s_width / 2 - space - rule, cx + s_width / 2 + space):
        draw.line([x0, rule_y, x0 + rule, rule_y], fill=RUST, width=max(2, sub_size // 12))
    return canvas


# ---------------------------------------------------------------------------------------- sheets


def arrow(draw: ImageDraw.ImageDraw, x: float, y: float, length: float, color=RUST, thickness: float = 10) -> None:
    head = thickness * 2.4
    draw.rectangle([x, y - thickness / 2, x + length - head, y + thickness / 2], fill=color)
    draw.polygon([(x + length - head, y - head * 0.75), (x + length, y), (x + length - head, y + head * 0.75)], fill=color)


def sheet(panels: list[tuple[Image.Image, str, str]], width: int = POSTER_WIDTH, gap: int = 44, margin: int = 40,
          label_size: int = 40, sub_size: int = 25, arrows: tuple[int, ...] = (), seed: int = 23) -> Image.Image:
    """Contact sheet built at its final width: images share one height on cream stock, each with a
    keyline and a two-line label. Type sizes are in output pixels, so labels stay readable when
    GitHub scales a 1600 px sheet down to the ~830 px README column."""
    lf, sf = font(label_size, BLACK), font(sub_size, BOLD)
    l_cap, s_cap = cap_height(lf), cap_height(sf)
    aspects = [im.width / im.height for im, _, _ in panels]
    height = round((width - 2 * margin - gap * (len(panels) - 1)) / sum(aspects))
    scaled = [(im.resize((round(height * a), height), Image.LANCZOS), la, sb) for (im, la, sb), a in zip(panels, aspects)]
    top_gap, mid_gap, bottom_gap = round(label_size * 0.7), round(label_size * 0.45), round(label_size * 0.75)
    H = margin + height + top_gap + l_cap + mid_gap + s_cap + bottom_gap
    canvas = paper((width, H), seed=seed)
    draw = ImageDraw.Draw(canvas)
    # One label size and one sublabel size per sheet: the largest that fits every panel.
    lsize, size = label_size, sub_size
    for im, label, sub in scaled:
        room = im.width + gap * 0.7
        while lsize > 16 and tracked_width(label, font(lsize, BLACK), lsize * 0.12) > room:
            lsize -= 1
        while size > 14 and tracked_width(sub, font(size, BOLD), size * 0.18) > room:
            size -= 1
    x = margin
    for i, (im, label, sub) in enumerate(scaled):
        canvas.paste(im, (x, margin))
        keyline(draw, (x, margin, x + im.width, margin + height))
        cx = x + im.width / 2
        l_base = margin + height + top_gap + l_cap
        draw_centered(draw, cx, l_base, label, font(lsize, BLACK), INK, tracking=lsize * 0.12)
        draw_centered(draw, cx, l_base + mid_gap + s_cap, sub, font(size, BOLD), RUST, tracking=size * 0.18)
        if i in arrows:
            arrow(draw, x + im.width + gap * 0.2, margin + height / 2, gap * 0.6, thickness=max(6, gap / 9))
        x += im.width + gap
    return canvas


def palette_strip(width: int = POSTER_WIDTH, height: int = 230, seed: int = 53) -> Image.Image:
    """The five inks of palette C07 as flat swatches with their names and hex values."""
    inks = [("CREAM", "#E4D9C6", CREAM), ("OCHRE", "#D9A05B", OCHRE), ("RUST", "#A6553B", RUST),
            ("SAGE-TEAL", "#4E6E63", (78, 110, 99)), ("NEAR-BLACK", "#2A2523", INK)]
    canvas = paper((width, height), seed=seed)
    draw = ImageDraw.Draw(canvas)
    margin, gap = 26, 14
    sw = (width - 2 * margin - gap * (len(inks) - 1)) / len(inks)
    nf, hf = font(26, BLACK), font(20, BOLD)
    for i, (name, hexcode, rgb) in enumerate(inks):
        x0 = round(margin + i * (sw + gap))
        x1 = round(x0 + sw)
        draw.rectangle([x0, margin, x1, height - 88], fill=rgb)
        keyline(draw, (x0, margin, x1, height - 88), width=1)
        cx = (x0 + x1) / 2
        draw_centered(draw, cx, height - 50, name, nf, INK, tracking=3)
        draw_centered(draw, cx, height - 22, hexcode, hf, RUST, tracking=3)
    return canvas


# ---------------------------------------------------------------------------------------- badges


def segments(mask_1d: np.ndarray, min_len: int, merge_gap: int) -> list[tuple[int, int]]:
    runs, start = [], None
    for i, v in enumerate(mask_1d):
        if v and start is None:
            start = i
        elif not v and start is not None:
            runs.append([start, i])
            start = None
    if start is not None:
        runs.append([start, len(mask_1d)])
    merged: list[list[int]] = []
    for r in runs:
        if merged and r[0] - merged[-1][1] <= merge_gap:
            merged[-1][1] = r[1]
        else:
            merged.append(r)
    return [(a, b) for a, b in merged if b - a >= min_len]


def slice_badges(grid: Image.Image, rows: int = 2, cols: int = 3) -> list[Image.Image]:
    grid = snap_alpha(grid)
    mask = np.array(grid.getchannel("A")) > 40
    row_runs = segments(mask.any(axis=1), min_len=80, merge_gap=10)
    if len(row_runs) != rows:
        raise SystemExit(f"expected {rows} badge rows, found {len(row_runs)}: {row_runs}")
    tiles = []
    for r0, r1 in row_runs:
        col_runs = segments(mask[r0:r1].any(axis=0), min_len=80, merge_gap=10)
        if len(col_runs) != cols:
            raise SystemExit(f"expected {cols} badges in row {r0}-{r1}, found {len(col_runs)}: {col_runs}")
        for c0, c1 in col_runs:
            tiles.append(square_pad(grid.crop((c0, r0, c1, r1)), pad=0.03))
    return tiles


# ------------------------------------------------------------------------------------------ save


def save_jpeg(img: Image.Image, path: Path, quality: int = 84) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    img.convert("RGB").save(path, "JPEG", quality=quality, optimize=True, progressive=True, subsampling="4:2:0")
    print(f"  {path}  {img.width}x{img.height}  {path.stat().st_size // 1024} KB")


def save_png(img: Image.Image, path: Path, colors: int | None = None) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    out = img
    if colors:
        out = img.quantize(colors=colors, method=Image.Quantize.FASTOCTREE, dither=Image.Dither.NONE)
    out.save(path, "PNG", optimize=True)
    print(f"  {path}  {img.width}x{img.height}  {path.stat().st_size // 1024} KB")


def thumb(img: Image.Image, width: int = THUMB_WIDTH) -> Image.Image:
    return img.resize((width, round(img.height * width / img.width)), Image.LANCZOS)


# ------------------------------------------------------------------------------------------ main


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--art", type=Path, required=True, help="directory with the raw generations")
    ap.add_argument("--out", type=Path, required=True, help="docs/assets")
    args = ap.parse_args()
    art, out = args.art, args.out
    open_art = lambda name: Image.open(art / name)  # noqa: E731

    print("logo")
    logo = square_pad(snap_alpha(open_art("logo-master.png")), pad=0.02).resize((512, 512), Image.LANCZOS)
    save_png(logo, out / "logo.png", colors=256)

    print("posters")
    hero = poster(open_art("hero.png"), *HERO_TITLE, title_size=72, sub_size=28, seed=5)
    save_jpeg(hero, out / "hero.jpg")
    for i, (key, (title, subtitle)) in enumerate(BANNERS.items()):
        banner = poster(open_art(f"banner-{key}.png"), title, subtitle, seed=31 + i)
        save_jpeg(banner, out / f"banner-{key}.jpg")
        save_jpeg(thumb(banner), out / "thumbs" / f"banner-{key}.jpg", quality=82)

    print("social preview")
    social = poster(open_art("hero.png"), HERO_TITLE[0], "IMAGE GENERATION FOR EVERY CODING AGENT  ·  NO API KEY",
                    width=1280, height=640, margin=22, crop_top=0.3, title_size=60, sub_size=24, seed=7)
    save_jpeg(social, out / "social-preview.jpg", quality=86)
    save_png(palette_strip(), out / "palette.png", colors=64)

    print("badges")
    for name, tile in zip(BADGES, slice_badges(open_art("badges-grid.png"))):
        save_png(tile.resize((256, 256), Image.LANCZOS), out / "badges" / f"{name}.png", colors=256)

    print("sheets")
    ratio_panels = []
    for key, label in (("1x1", "1 : 1"), ("16x9", "16 : 9"), ("9x16", "9 : 16")):
        im = open_art(f"ratio-{key}.png").convert("RGB")
        ratio_panels.append((im, label, f"{im.width} × {im.height} PX"))
    save_jpeg(sheet(ratio_panels, seed=41), out / "examples" / "aspect-ratios.jpg")

    green = open_art("balloon-greenscreen-v2.png").convert("RGB")
    cut = snap_alpha(open_art("balloon-cutout.png"))
    save_jpeg(
        sheet([(green, "GENERATED", "ON A FLAT #00FF00 BACKDROP"), (on_checkerboard(cut, 40), "CUT OUT LOCALLY", "REMOVE_BACKGROUND  ·  NO QUOTA")],
              width=1400, gap=150, arrows=(0,), seed=43),
        out / "examples" / "remove-background.jpg",
    )
    save_png(square_pad(cut, 0.04).resize((640, 640), Image.LANCZOS), out / "examples" / "balloon-cutout.png", colors=256)

    s = art / "session"
    shop = Image.open(s / "hero.png").convert("RGB")
    sticker = on_checkerboard(snap_alpha(Image.open(s / "cactus-sticker.png")), 40)
    hat = on_checkerboard(snap_alpha(Image.open(s / "cactus-sticker-hat.png")), 40)
    save_jpeg(
        sheet([(sticker, "GENERATE_IMAGE", "TRANSPARENT STICKER"), (hat, "EDIT_IMAGE", "ADD A STRAW HAT"),
               (shop, "GENERATE_IMAGE", "16 : 9 LANDING HERO")], gap=90, arrows=(0,), seed=47),
        out / "examples" / "real-session.jpg",
    )


if __name__ == "__main__":
    main()
